#!/usr/bin/env bash


set -o nounset \
    -o errexit \
    -o verbose \
    -o xtrace


# Set environment values if they exist as arguments
if [ $# -ne 0 ]; then
  echo "===> Overriding env params with args ..."
  for var in "$@"
  do
    export "$var"
  done
fi

echo "===> ENV Variables ..."
env | sort

echo "===> User"
id

echo "===> Configuring ..."
/usr/lib/kafka/docker/bin/configure

echo "===> Running preflight checks ... "
/usr/lib/kafka/docker/bin/ensure

echo "===> Launching ... "
exec /usr/lib/kafka/docker/bin/launch
